--------------------------------------------------------
--  File creato - domenica-settembre-09-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARTA
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."CARTA" 
   (	"ID_CARTA" NUMBER, 
	"TIPO_CARTA" VARCHAR2(20 BYTE), 
	"TESTO" VARCHAR2(2000 BYTE), 
	"IMPORTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CASELLA
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."CASELLA" 
   (	"ID_CASELLA" NUMBER, 
	"NOME" VARCHAR2(30 BYTE), 
	"POSIZIONE" NUMBER(*,0), 
	"TIPO_CASELLA" VARCHAR2(20 BYTE), 
	"TIPO_NONED" VARCHAR2(20 BYTE), 
	"COLORE" VARCHAR2(20 BYTE), 
	"TESTO" VARCHAR2(2000 BYTE), 
	"PREZZO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTRATTO
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."CONTRATTO" 
   (	"ID_CONTRATTO" NUMBER, 
	"NOME" VARCHAR2(30 BYTE), 
	"TIPO_CONTRATTO" VARCHAR2(20 BYTE), 
	"VALIPOTECARIO" NUMBER(*,0), 
	"COLORE" VARCHAR2(20 BYTE), 
	"RENDITASEMPLICE" NUMBER(*,0), 
	"RENDITA1CASA" NUMBER(*,0), 
	"RENDITA2CASE" NUMBER(*,0), 
	"RENDITA3CASE" NUMBER(*,0), 
	"RENDITA4CASE" NUMBER(*,0), 
	"RENDITAALBERGO" NUMBER(*,0), 
	"PREZZOACQUISTOED" NUMBER(*,0), 
	"TIPO_NONED" VARCHAR2(20 BYTE), 
	"RENDITA2STAZIONI" NUMBER(*,0), 
	"RENDITA3STAZIONI" NUMBER(*,0), 
	"RENDITA4STAZIONI" NUMBER(*,0), 
	"RENDITA2SOCIETA" NUMBER(*,0), 
	"PREZZO" NUMBER(*,0), 
	"ID_CASELLA" NUMBER, 
	"TESTO1SOCIETA" VARCHAR2(2000 BYTE), 
	"TESTO2SOCIETA" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GIOCATORE
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."GIOCATORE" 
   (	"ID_GIOCATORE" NUMBER, 
	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOSSA
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."MOSSA" 
   (	"ID_MOSSA" NUMBER, 
	"TURNO" NUMBER(*,0), 
	"ORDINE" NUMBER(*,0), 
	"TIPO_MOSSA" VARCHAR2(20 BYTE), 
	"DADO1" NUMBER(*,0), 
	"DADO2" NUMBER(*,0), 
	"TIPO_PAGAMENTO" VARCHAR2(20 BYTE), 
	"PAGAMENTO_DATO" NUMBER(*,0), 
	"PAGAMENTO_RICEVUTO" NUMBER(*,0), 
	"ID_PARTITA" NUMBER, 
	"ID_GIOCATORE" NUMBER, 
	"CASELLA_PARTENZA" NUMBER, 
	"CASELLA_ARRIVO" NUMBER, 
	"ID_POSSEDIMENTO" NUMBER, 
	"ID_CARTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGAMENTO_GIOCATORE
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."PAGAMENTO_GIOCATORE" 
   (	"ID_MOSSA" NUMBER, 
	"ID_GIOCATORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARTITA
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."PARTITA" 
   (	"ID_PARTITA" NUMBER, 
	"NUMGIOCATORI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARTITA_GIOCATORE
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."PARTITA_GIOCATORE" 
   (	"PARTITA" NUMBER, 
	"GIOCATORE" NUMBER, 
	"CONTO" NUMBER(*,0), 
	"PEDINA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSSEDIMENTO
--------------------------------------------------------

  CREATE TABLE "DB_MONO"."POSSEDIMENTO" 
   (	"ID_POSSEDIMENTO" NUMBER, 
	"TIPO_POSSEDIMENTO" VARCHAR2(20 BYTE), 
	"NUM_CASA" NUMBER(*,0) DEFAULT 0, 
	"ID_CONTRATTO" NUMBER, 
	"ID_GIOCATORE" NUMBER, 
	"NOME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CARTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."CARTA_PK" ON "DB_MONO"."CARTA" ("ID_CARTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CASELLA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."CASELLA_PK" ON "DB_MONO"."CASELLA" ("ID_CASELLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CASELLA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."CASELLA_UK1" ON "DB_MONO"."CASELLA" ("POSIZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTRATTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."CONTRATTO_PK" ON "DB_MONO"."CONTRATTO" ("ID_CONTRATTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTRATTO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."CONTRATTO_UK1" ON "DB_MONO"."CONTRATTO" ("ID_CASELLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GIOCATORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."GIOCATORE_PK" ON "DB_MONO"."GIOCATORE" ("ID_GIOCATORE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MOSSA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."MOSSA_PK" ON "DB_MONO"."MOSSA" ("ID_MOSSA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARTITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."PARTITA_PK" ON "DB_MONO"."PARTITA" ("ID_PARTITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSSEDIMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."POSSEDIMENTO_PK" ON "DB_MONO"."POSSEDIMENTO" ("ID_POSSEDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_MONO"."UK1" ON "DB_MONO"."PARTITA_GIOCATORE" ("PARTITA", "PEDINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_CARTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_CARTA" 
BEFORE DELETE ON CARTA
FOR EACH ROW
BEGIN
DELETE FROM MOSSA WHERE ID_CARTA=:OLD.ID_CARTA;

END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_CARTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_CASELLA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_CASELLA" 
BEFORE DELETE ON CASELLA
FOR EACH ROW
BEGIN
DELETE FROM CONTRATTO WHERE ID_CASELLA=:OLD.ID_CASELLA;
DELETE FROM MOSSA WHERE CASELLA_ARRIVO=:OLD.ID_CASELLA OR CASELLA_PARTENZA=:OLD.ID_CASELLA;
END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_CASELLA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_CONTRATTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_CONTRATTO" 
BEFORE DELETE ON CONTRATTO
FOR EACH ROW
BEGIN
DELETE FROM POSSEDIMENTO WHERE ID_CONTRATTO=:OLD.ID_CONTRATTO;

END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_CONTRATTO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_GIOCATORE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_GIOCATORE" 
BEFORE DELETE ON GIOCATORE
FOR EACH ROW
BEGIN
DELETE FROM POSSEDIMENTO WHERE ID_GIOCATORE=:OLD.ID_GIOCATORE;
DELETE FROM PARTITA_GIOCATORE WHERE GIOCATORE=:OLD.ID_GIOCATORE;
DELETE FROM PAGAMENTO_GIOCATORE WHERE ID_GIOCATORE=:OLD.ID_GIOCATORE;
DELETE FROM MOSSA WHERE ID_GIOCATORE=:OLD.ID_GIOCATORE;
END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_GIOCATORE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_MOSSA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_MOSSA" 
BEFORE DELETE ON MOSSA
FOR EACH ROW
BEGIN
DELETE FROM PAGAMENTO_GIOCATORE WHERE ID_MOSSA=:OLD.ID_MOSSA;
END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_MOSSA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_PARTITA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_PARTITA" 
BEFORE DELETE ON PARTITA
FOR EACH ROW
BEGIN
DELETE FROM MOSSA WHERE ID_PARTITA=:OLD.ID_PARTITA;
DELETE FROM PARTITA_GIOCATORE WHERE PARTITA=:OLD.ID_PARTITA;
END;


/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_PARTITA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CANCELLAZIONE_POSSEDIMENTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_MONO"."CANCELLAZIONE_POSSEDIMENTO" 
BEFORE DELETE ON POSSEDIMENTO
FOR EACH ROW
BEGIN
DELETE FROM MOSSA WHERE ID_POSSEDIMENTO=:OLD.ID_POSSEDIMENTO;
END;
/
ALTER TRIGGER "DB_MONO"."CANCELLAZIONE_POSSEDIMENTO" ENABLE;
--------------------------------------------------------
--  Constraints for Table CARTA
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."CARTA" MODIFY ("IMPORTO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CARTA" ADD CONSTRAINT "CARTA_CHK1" CHECK (TIPO_CARTA IN ('IMPREVISTI','PROBABILITÀ')) ENABLE;
  ALTER TABLE "DB_MONO"."CARTA" MODIFY ("TESTO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CARTA" MODIFY ("TIPO_CARTA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CARTA" ADD CONSTRAINT "CARTA_PK" PRIMARY KEY ("ID_CARTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."CARTA" MODIFY ("ID_CARTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CASELLA
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_UK1" UNIQUE ("POSIZIONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_CHK5" CHECK (POSIZIONE BETWEEN 1 AND 40) ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_CHK3" CHECK (COLORE IN ('FUCSIA','CELESTE','ARANCIONE','MARRONE','ROSSO','GIALLO','VERDE','BLU')) ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_CHK4" CHECK ((TIPO_CASELLA = 'NON EDIFICABILE' AND COLORE IS NULL AND TESTO IS NULL AND PREZZO IS NOT NULL  AND TIPO_NONED IS NOT NULL ) OR (TIPO_CASELLA = 'IMPREVISTI' AND COLORE IS NULL AND TESTO IS NULL AND PREZZO IS NULL AND TIPO_NONED IS NULL)  OR (TIPO_CASELLA = 'TERRITORIO' AND COLORE IS NOT NULL AND TESTO IS NULL AND PREZZO IS NOT NULL AND TIPO_NONED IS NULL) OR  (TIPO_CASELLA = 'SPECIALE' AND TESTO IS NOT NULL AND PREZZO IS NOT NULL AND COLORE IS NULL AND TIPO_NONED IS NULL) OR (TIPO_CASELLA = 'PROBABILITÀ' AND COLORE IS NULL AND TESTO IS NULL AND PREZZO IS NULL AND TIPO_NONED IS NULL)) ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_CHK2" CHECK (TIPO_NONED IN ('FERROVIA','SOCIETÀ')) ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_CHK1" CHECK (TIPO_CASELLA IN ('NON EDIFICABILE','SPECIALE','TERRITORIO','PROBABILITÀ','IMPREVISTI')) ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" ADD CONSTRAINT "CASELLA_PK" PRIMARY KEY ("ID_CASELLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."CASELLA" MODIFY ("TIPO_CASELLA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CASELLA" MODIFY ("POSIZIONE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CASELLA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CASELLA" MODIFY ("ID_CASELLA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRATTO
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_UK1" UNIQUE ("ID_CASELLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_CHK2" CHECK (COLORE IN ('FUCSIA','CELESTE','ARANCIONE','MARRONE','ROSSO','GIALLO','VERDE','BLU')) ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_CHK4" CHECK ((TIPO_CONTRATTO='EDIFICABILE' AND COLORE IS NOT NULL AND RENDITA1CASA IS NOT NULL AND RENDITA2CASE IS NOT NULL AND RENDITA3CASE IS NOT NULL AND RENDITA4CASE IS NOT NULL AND RENDITAALBERGO IS NOT NULL AND PREZZOACQUISTOED IS NOT NULL AND TIPO_NONED IS NULL AND RENDITA2STAZIONI IS NULL AND RENDITA3STAZIONI IS NULL AND RENDITA4STAZIONI IS NULL AND RENDITA2SOCIETA IS NULL AND TESTO1SOCIETA IS NULL AND TESTO2SOCIETA IS NULL)
 OR 
(TIPO_CONTRATTO='NON EDIFICABILE' AND COLORE IS NULL AND RENDITA1CASA IS NULL AND RENDITA2CASE IS NULL AND RENDITA3CASE IS NULL AND RENDITA4CASE IS NULL AND RENDITAALBERGO IS NULL AND PREZZOACQUISTOED IS NULL AND TIPO_NONED='SOCIETÀ' AND RENDITA2STAZIONI IS NULL AND RENDITA3STAZIONI IS NULL AND RENDITA4STAZIONI IS NULL AND RENDITA2SOCIETA IS NOT NULL AND TESTO1SOCIETA IS NOT NULL AND TESTO2SOCIETA IS NOT NULL) 
OR
 (TIPO_CONTRATTO='NON EDIFICABILE' AND COLORE IS NULL AND RENDITA1CASA IS NULL AND RENDITA2CASE IS NULL AND RENDITA3CASE IS NULL AND RENDITA4CASE IS NULL AND RENDITAALBERGO IS NULL AND PREZZOACQUISTOED IS NULL AND TIPO_NONED='FERROVIA' AND RENDITA2STAZIONI IS NOT NULL AND RENDITA3STAZIONI IS NOT NULL AND RENDITA4STAZIONI IS NOT NULL AND RENDITA2SOCIETA IS NULL AND TESTO1SOCIETA IS NULL AND TESTO2SOCIETA IS NULL)) ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("RENDITASEMPLICE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_PK" PRIMARY KEY ("ID_CONTRATTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_CHK3" CHECK (TIPO_NONED IN ('FERROVIA','SOCIETÀ')) ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("ID_CASELLA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("PREZZO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_CHK1" CHECK (TIPO_CONTRATTO IN ('EDIFICABILE','NON EDIFICABILE')) ENABLE;
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("VALIPOTECARIO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("TIPO_CONTRATTO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."CONTRATTO" MODIFY ("ID_CONTRATTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GIOCATORE
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."GIOCATORE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."GIOCATORE" ADD CONSTRAINT "GIOCATORE_PK" PRIMARY KEY ("ID_GIOCATORE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."GIOCATORE" MODIFY ("ID_GIOCATORE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOSSA
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_CHK3" CHECK ((TIPO_MOSSA='MOVIMENTO' AND DADO1 IS NOT NULL AND DADO2 IS NOT NULL AND TIPO_PAGAMENTO IS NULL AND PAGAMENTO_DATO IS NULL AND PAGAMENTO_RICEVUTO IS NULL AND CASELLA_PARTENZA IS NOT NULL AND CASELLA_ARRIVO IS NOT NULL AND ID_POSSEDIMENTO IS NULL)
OR
(TIPO_MOSSA='PAGAMENTO' AND DADO1 IS NULL AND DADO2 IS NULL AND CASELLA_ARRIVO IS NULL AND CASELLA_PARTENZA IS NULL AND PAGAMENTO_DATO IS NOT NULL AND  PAGAMENTO_RICEVUTO IS NOT NULL AND TIPO_PAGAMENTO IS NOT NULL)) ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("ID_GIOCATORE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("ID_PARTITA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_CHK2" CHECK (TIPO_PAGAMENTO IN ('GENERICO','VERSO BANCA','VERSO GIOCATORE')) ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_CHK1" CHECK (TIPO_MOSSA IN ('MOVIMENTO','PAGAMENTO')) ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_PK" PRIMARY KEY ("ID_MOSSA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("TIPO_MOSSA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("ORDINE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("TURNO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" MODIFY ("ID_MOSSA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_CHK8" CHECK (DADO2 BETWEEN 1 AND 6) ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_CHK7" CHECK (DADO1 BETWEEN 1 AND 6) ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGAMENTO_GIOCATORE
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."PAGAMENTO_GIOCATORE" MODIFY ("ID_GIOCATORE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."PAGAMENTO_GIOCATORE" MODIFY ("ID_MOSSA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTITA
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."PARTITA" ADD CONSTRAINT "PARTITA_CHK1" CHECK (NUMGIOCATORI BETWEEN 2 AND 6) ENABLE;
  ALTER TABLE "DB_MONO"."PARTITA" MODIFY ("NUMGIOCATORI" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."PARTITA" ADD CONSTRAINT "PARTITA_PK" PRIMARY KEY ("ID_PARTITA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."PARTITA" MODIFY ("ID_PARTITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTITA_GIOCATORE
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" MODIFY ("GIOCATORE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" MODIFY ("PARTITA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" ADD CONSTRAINT "UK1" UNIQUE ("PARTITA", "PEDINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" ADD CONSTRAINT "PARTITA_GIOCATORE_CHK1" CHECK (PEDINA IN ('BARCA','AUTOMOBILE','CAPPELLO','SCARPONE','FERRO DA STIRO','CANE','CARRIOLA', 'DITALE')) ENABLE;
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" MODIFY ("PEDINA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" MODIFY ("CONTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSSEDIMENTO
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_CHK3" CHECK ((TIPO_POSSEDIMENTO='SEMPLICE' AND NUM_CASA=0) 
OR 
(TIPO_POSSEDIMENTO='IPOTECATA' AND NUM_CASA=0) 
OR 
(TIPO_POSSEDIMENTO='ALBERGO' AND NUM_CASA=0) 
OR (TIPO_POSSEDIMENTO='CASA' AND NUM_CASA BETWEEN 1 AND 4)) ENABLE;
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_CHK2" CHECK (NUM_CASA BETWEEN 0 AND 4
) ENABLE;
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_CHK1" CHECK (TIPO_POSSEDIMENTO IN ('SEMPLICE','CASA','ALBERGO','IPOTECATA')) ENABLE;
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_PK" PRIMARY KEY ("ID_POSSEDIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("ID_GIOCATORE" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("ID_CONTRATTO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("NUM_CASA" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("TIPO_POSSEDIMENTO" NOT NULL ENABLE);
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" MODIFY ("ID_POSSEDIMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTRATTO
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."CONTRATTO" ADD CONSTRAINT "CONTRATTO_FK1" FOREIGN KEY ("ID_CASELLA")
	  REFERENCES "DB_MONO"."CASELLA" ("ID_CASELLA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOSSA
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK1" FOREIGN KEY ("ID_PARTITA")
	  REFERENCES "DB_MONO"."PARTITA" ("ID_PARTITA") ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK2" FOREIGN KEY ("ID_GIOCATORE")
	  REFERENCES "DB_MONO"."GIOCATORE" ("ID_GIOCATORE") ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK3" FOREIGN KEY ("CASELLA_PARTENZA")
	  REFERENCES "DB_MONO"."CASELLA" ("ID_CASELLA") ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK4" FOREIGN KEY ("CASELLA_ARRIVO")
	  REFERENCES "DB_MONO"."CASELLA" ("ID_CASELLA") ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK5" FOREIGN KEY ("ID_POSSEDIMENTO")
	  REFERENCES "DB_MONO"."POSSEDIMENTO" ("ID_POSSEDIMENTO") ENABLE;
  ALTER TABLE "DB_MONO"."MOSSA" ADD CONSTRAINT "MOSSA_FK6" FOREIGN KEY ("ID_CARTA")
	  REFERENCES "DB_MONO"."CARTA" ("ID_CARTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGAMENTO_GIOCATORE
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."PAGAMENTO_GIOCATORE" ADD CONSTRAINT "PAGAMENTO_GIOCATORE_FK1" FOREIGN KEY ("ID_MOSSA")
	  REFERENCES "DB_MONO"."MOSSA" ("ID_MOSSA") ENABLE;
  ALTER TABLE "DB_MONO"."PAGAMENTO_GIOCATORE" ADD CONSTRAINT "PAGAMENTO_GIOCATORE_FK2" FOREIGN KEY ("ID_GIOCATORE")
	  REFERENCES "DB_MONO"."GIOCATORE" ("ID_GIOCATORE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTITA_GIOCATORE
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" ADD CONSTRAINT "PARTITA_GIOCATORE_FK1" FOREIGN KEY ("PARTITA")
	  REFERENCES "DB_MONO"."PARTITA" ("ID_PARTITA") ENABLE;
  ALTER TABLE "DB_MONO"."PARTITA_GIOCATORE" ADD CONSTRAINT "PARTITA_GIOCATORE_FK2" FOREIGN KEY ("GIOCATORE")
	  REFERENCES "DB_MONO"."GIOCATORE" ("ID_GIOCATORE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSSEDIMENTO
--------------------------------------------------------

  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_FK1" FOREIGN KEY ("ID_GIOCATORE")
	  REFERENCES "DB_MONO"."GIOCATORE" ("ID_GIOCATORE") ENABLE;
  ALTER TABLE "DB_MONO"."POSSEDIMENTO" ADD CONSTRAINT "POSSEDIMENTO_FK2" FOREIGN KEY ("ID_CONTRATTO")
	  REFERENCES "DB_MONO"."CONTRATTO" ("ID_CONTRATTO") ENABLE;
